
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 27 16:26:45 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int MINUS = 5;
  public static final int MOD = 8;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int DIV = 7;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int EXPO = 9;
  public static final int MUL = 6;
  public static final int LPAREN = 2;
}

